# ~/.zshrc

EDITOR=nvim
git config --global core.editor "nvim"

# history defaults
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# load all the files in .dotfiles/zsh/aliases
for file in ~/.dotfiles/zsh/aliases/*.zsh; do
    source $file
done

# prompt
eval "$(starship init zsh)"

# antigen plugins
source ~/.antidote/antidote.zsh
antidote load

# zsh-history-substring-search configuration
bindkey '^[[A' history-substring-search-up # or '\eOA'
bindkey '^[[B' history-substring-search-down # or '\eOB'
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
HISTORY_SUBSTRING_SEARCH_FUZZY=1
